### ISSUE TITLE
invalid memory reference & in __advance_MOD_time_marching2.constprop.0

### ISSUE THREAD

**Issue by college301654-art** [ucns3d-team/UCNS3D#52]
**Describe the bug**
When I first run ucns3d_p in the example of 2D double Mach reflection, a problem of invalid memory reference below occurs.
It seems that array out-of-bounds is related to memory. But in the run of 3D taylor-green-vortex case, this problem will not occur.
Is there anyone to help solve this problem？
=====================================================
UCNS3D Running

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:
#0  0x7ff94a623ad0 in ???
#1  0x7ff94a622c35 in ???
#2  0x7ff94a24251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0x7f2f88223ad0 in ???
#1  0x7f2f88222c35 in ???
#2  0x7f2f87e4251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x55d4b233af1a in __advance_MOD_runge_kutta4_2d
	at /home/UCNS3D-master/src/time_p.f90:2684
#4  0x55d4b233af1a in __advance_MOD_time_marching2.constprop.0
	at /home/UCNS3D-master/src/time_p.f90:4567
#5  0x7ff94a1caa15 in ???
#3  0x558618912f1a in __advance_MOD_runge_kutta4_2d
	at /home/UCNS3D-master/src/time_p.f90:2684
#4  0x558618912f1a in __advance_MOD_time_marching2.constprop.0
	at /home/UCNS3D-master/src/time_p.f90:4567
#5  0x7f2f8856db9d in ???
#6  0x7f2f87e94b42 in start_thread
	at ./nptl/pthread_create.c:442
#7  0x7f2f87f269ff in ???
	at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
#8  0xffffffffffffffff in ???
#6  0x55d4b23072fc in ucns3d
	at /home/UCNS3D-master/src/main.f90:827
#7  0x55d4b225817e in main
	at /home/UCNS3D-master/src/main.f90:8
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node lz-Super-Server exited on signal 11 (Segmentation fault).

**Comment by college301654-art** [comment]
When the time-advance format changes from RK4 to RK3, this problem will be solved. But how can I improve this problem?

**Comment by TakisCFD** [comment]
Attach the UCNS3D.DAT file used since if the correct options are not selected it can lead to these issues.

**Comment by college301654-art** [comment]
> Attach the UCNS3D.DAT file used since if the correct options are not selected it can lead to these issues.

Yes, the problem is solved with the UCNS3D.DAT attached.

**Comment by TakisCFD** [comment]
no attachment found
